spring:
#   redis:
#     host: 172.17.0.1
#     #assword: 123456
#     port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    druid:
      url: jdbc:mysql://47.102.99.93:3306/spcloud
      username: dawei
      password: WEIxy.789
  application:
    name: springcloud-provider-config
  profiles:
    active: test
logging:
  level:
    root: info
    org.hibernate : info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.yasaka.stock : debug
server:
  port: 5681